name: CronMonitor
options:
  bundleIdPrefix: com.local
  deploymentTarget:
    macOS: "14.0"
targets:
  CronMonitor:
    type: application
    platform: macOS
    sources:
      - Sources/CronMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.local.cronmonitor
        PRODUCT_NAME: CronMonitor
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ENABLE_APP_SANDBOX: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  CronMonitorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/CronMonitorTests
    dependencies:
      - target: CronMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.local.cronmonitor.tests
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
